name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --omit=dev
          npm run build --if-present
        env:
          CI: true
      - name: Zip
        run: |
          mkdir -p dist_bundle
          cp -r dist/lambda dist_bundle
          zip -qq -r bundle.zip dist_bundle node_modules
        env:
          CI: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda_bundle
          path: bundle.zip
      - name: Default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-2
          function_name: YES_Scraper
          zip_file: bundle.zip
